config/routes.rb
Rails.application.routes.draw do

  get 'presentation/show'

  root 'home#index', as: :home
  get 'presentation' => 'presentation#show', as: :presentation

  devise_for :users
  ActiveAdmin.routes(self)

  resources :firms
  get 'firms/:id/round/:round_id/ownership' => "firms#ownership", as: :ownership
  post 'firms/:id/round/:round_id/ownership' => "firms#update_ownership", as: :update_ownership
  get 'firms/:id/cap_table' => "firms#cap_table", as: :cap_table

  resources :shareholders, only: [:show, :edit, :update]
  get 'firms/:id/round/:round_id/shareholders' => 'shareholders#new', as: :new_shareholder
  post 'firms/:id/round/:round_id/shareholders/' => 'shareholders#create', as: :create_shareholder
  delete 'firms/:id/round/:round_id/shareholders/:shareholder_id' => 'shareholders#destroy', as: :delete_shareholder

  resources :rounds, only: [:edit, :update, :destroy]
  get 'firms/:id/rounds/new' => 'rounds#new', as: :new_round
  get 'firm/:id/round/:round_id' => 'rounds#show', as: :show_round
  post 'firm/:id/rounds' => 'rounds#create', as: :create_round
  get 'firms/:id/rounds' => 'rounds#index', as: :rounds

  get 'firms/:id/round/:round_id/subscription_forms' => 'subscription_forms#index', as: :subscription_forms
  get 'firms/:id/round/:round_id/subscription_form/:shareholder_id/:investment_id' => 'subscription_forms#show', as: :subscription_form
  get 'firms/:id/round/:round_id/subscription_form/zip' => 'subscription_forms#zip_form', as: :zip_form
end

app/models/firm.rb
class Firm < ActiveRecord::Base
  has_many :rounds
  has_many :shareholders
  has_many :investments
  belongs_to :user

  validates_presence_of :name, :initial_capital


end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController

  before_action :find_firm, only: [:show, :edit, :update, :destroy, :cap_table, :shareholders, :create_shareholder, :ownership, :update_ownership, :refresh_financial_infos]
  before_action :find_round, only: [:ownership, :update_ownership]
  before_action :authenticate_user!
  respond_to :js, :html

  def index
    @firms = Firm.all
  end

  def show
    authorize @firm
    @shareholders = @firm.shareholders
    if @firm.rounds == 1
      @shares = @shareholders.sum("shares")
    end
  end

  def cap_table
    authorize @firm
    @round = @firm.rounds.last
    respond_to do |format|
      format.xls
      format.html
    end
  end

  def new
    @firm = Firm.new
  end

  def create
    @firm = Firm.new(firm_params)
    if @firm.valid?
      @firm.save
      @round = Round.create(firm_id: @firm.id, name: "Situation initiale pré-levée")
      @round.update_attribute(:initial_round, true)
      redirect_to new_shareholder_path(@firm.id, @round.id)
    else
     flash.now[:danger] = @firm.errors.full_messages
     render :new
   end
  end

  def edit
    @round = @firm.rounds.last if @firm.shareholders.any?
  end

  def update
    authorize @firm
    @firm.update(firm_params)
    redirect_to add_shareholders_path(@firm)
  end

  def destroy
    authorize @firm
    @firm.destroy
    redirect_to firms_path
  end

  def ownership
    authorize @firm
    @shareholders = @firm.shareholders
  end

  def update_ownership
    # for initial investors
    if @round.initial_round
      params[:shareholder].keys.each do |id|
        @shareholder = Shareholder.find(id.to_i)
        @shareholder.update_attributes(set_shares(id))
        @shareholder.update_attribute(:corrected_shares, @shareholder.shares.floor)
      end
      setup_financial_infos(@firm)

      @firm.shareholders.each do |shareholder|
        if shareholder.initial_investor
          Investment.create(firm_id: @firm.id, round_id: @round.id, shareholder_id: shareholder.id, amount: (shareholder.shares * @firm.nominal_value))
        end
      end

    # for new investors
    else
      params[:shareholder].each do |shareholder_id, investment|
        next if investment["amount"].blank?
        @shareholder = Shareholder.find(shareholder_id)
        @shareholder.investments.create(investment.delete_if { |k, v| !%w(amount round_id firm_id).include? k })
      end
      compute_new_value(@firm, @round)
      compute_new_shares(@firm, @round)
    end
    if @firm.rounds.last.initial_round
      redirect_to new_round_path(@firm)
    else
      redirect_to show_round_path(@firm.id, @round.id)
    end

  end

  def setup_financial_infos(firm)
    firm.update_attribute(:shares, firm.shareholders.sum("shares"))
    firm.update_attribute(:nominal_value, firm.initial_capital/firm.shares)
  end

  def compute_new_value(firm, round)
    round.update_attribute(:amount_raised, round.investments.sum("amount"))
    firm.update_attribute(:pre_valuation, (round.amount_raised/(round.ownership_offered/100) - round.amount_raised))
    firm.update_attribute(:real_value, firm.pre_valuation/firm.shares)
    firm.update_attribute(:premium, firm.real_value - firm.nominal_value)
    firm.update_attribute(:post_valuation, firm.pre_valuation + round.amount_raised)
  end

  def compute_new_shares(firm, round)
    new_outstanding_shares = firm.shares
    round.shareholders.each do |shareholder|
      shareholder.update_attribute(:shares, shareholder.investments.last.amount / firm.real_value)
      shareholder.update_attribute(:corrected_shares, shareholder.shares.floor)
      shareholder.update_attribute(:non_subscribed_amount, (shareholder.shares - shareholder.corrected_shares)*firm.real_value)
      Investment.where(round_id: round.id).where(shareholder_id: shareholder.id).last.update_attribute(:real_amount, (shareholder.corrected_shares * @firm.real_value).round(2))
      new_outstanding_shares += shareholder.corrected_shares
    end

    firm.update_attribute(:shares, new_outstanding_shares)
    round.update_attribute(:real_amount_raised, (firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.real_value).round(2))
    round.update_attribute(:shares_issued, @firm.shareholders.where(initial_investor: false).sum('corrected_shares'))
  end

  private

    def firm_params
      params.require(:firm).permit(:name, :official_address, :rcs, :court_service,
             :bank_name, :bank_agency, :bank_agency_address, :bank_account, :valuation,
             :share_price, :initial_capital, :shares, :user_id, :city, :postal_code, :country)
    end

    def find_firm
      @firm = Firm.find(params[:id])
    end

    def find_round
      @round = Round.find(params[:round_id])
    end

    def investment_params
      params.require(:shareholder).fetch(id).permit(investment_attributes: [:round_id, :firm_id, :amount])
    end

    def set_shares(id)
      params.require(:shareholder).fetch(id).permit(:shares)
    end

end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/views/firms/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
  <%= form_for @firm do |f| %>

    <legend>1. Informations de la société</legend>
    <div class="row">
      <div class="form-group">
        <%= f.label :name, "Nom de la société", class: "control-label col-sm-3 text-right" %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control", placeholder: "Nom de la société" %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :rcs, "Numéro RCS", class: "control-label col-sm-3 text-right" %>
        <div class="col-sm-4">
          <%= f.text_field :rcs, class: "form-control", placeholder: "Numéro RCS" %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :court_service, "Greffe", class: "control-label col-sm-3 text-right" %>
        <div class="col-sm-9">
          <%= f.text_field :court_service, class: "form-control", placeholder: "Ville du greffe d'immatriculation" %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :initial_capital, "Capital social initial", class: "control-label col-sm-3 text-right" %>
        <div class="col-sm-4">
          <%= f.number_field :initial_capital, class: "form-control", placeholder: "Capital social (€)" %>
        </div>
      </div>
    </div>
    <br>
    <br>

    <legend>2. Adresse du siège social</legend>
      <div class="row">
        <div class="form-group">
          <%= f.label :official_address, "Adresse", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-9">
            <%= f.text_area :official_address, class: "form-control", placeholder: "Adresse (numéro et nom de la voie)" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :city, "Ville", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-4">
            <%= f.text_field :city, class: "form-control", placeholder: "Ville" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :postal_code, "Code postal", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-4">
            <%= f.text_field :postal_code, class: "form-control", placeholder: "Code postal" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :country, "Pays", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-4">
            <%= f.text_field :country, class: "form-control", placeholder: "Pays" %>
          </div>
        </div>
      </div>
      <br>
      <br>

    <legend>3. Informations bancaires</legend>
      <div class="row">
        <div class="form-group">
          <%= f.label :bank_name, "Nom de la banque", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-6">
            <%= f.text_field :bank_name, class: "form-control", placeholder: "Nom de la banque" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :bank_agency, "Nom de l'agence bancaire", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-9">
            <%= f.text_field :bank_agency, class: "form-control", placeholder: "Nom de l'agence bancaire" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :bank_agency_address, "Nom de l'agence bancaire", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-9">
            <%= f.text_area :bank_agency_address, class: "form-control", placeholder: "Adresse complète de l'agence bancaire (voie, ville, code postal)" %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="form-group">
          <%= f.label :bank_account, "Compte bancaire", class: "control-label col-sm-3 text-right" %>
          <div class="col-sm-9">
            <%= f.text_field :bank_account, class: "form-control", placeholder: "Numéro de compte bancaire de la société" %>
          </div>
        </div>
      </div>
      <br>
      <br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="row last-row">
      <% if @firm.shareholders.any? %>
        <div class="col-sm-4">
          <%= f.submit "Modifier les infos des actionnaires existants", class: 'btn btn-primary border-bottom' %>
        </div>
        <div class="col-sm-4 col-sm-offset-1">
          <%= button_to "Définir la répartition du capital", ownership_path(@firm, @round), method: 'get', class: 'btn btn-primary border-bottom' %>
        </div>
      <% else %>
        <div class="col-sm-6 col-sm-offset-3">
          <%= f.submit "Ajouter les actionnaires pré-levée", class: 'btn btn-primary border-bottom' %>
        </div>
      <% end %>
  <% end %>
  </div>

  </div>
</div>

app/views/firms/cap_table.html.erb
<div class="cap-table-container">

<div class="row">
  <div class="col-sm-6">
    <p class="lead">Tableau de capitalisation de <%= @firm.name %></p>
  </div>
  <div class="col-sm-3">
    <div class="po-markup">
      <a href=<%= cap_table_path(format: "pdf")%> class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Télécharger au format PDF</a>
    </div>
  </div>
  <div class="col-sm-3 pull-right">
    <a href=<%= cap_table_path(format: "xls")%> class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Télécharger au format Excel</a>
  </div>
</div>
<div class="row doc-link">
  <div class="col-sm-12">
    <%= link_to "Revenir aux documents", show_round_path(@firm.id, @round.id) %>
  </div>
</div>
<br>
<br>
<table class="table table-hover table-bordered table-condensed">
  <tr class="info">
    <th>Nom</th>
    <th>Capital social pre-AK (€)</th>
    <th>Nombre d'actions pre-AK</th>
    <th>% capital social pre-AK</th>
    <th>Souscription AK (€)</th>
    <th>Nombre d'actions nouvelles</th>
    <th>Nombre corrigé d'actions (rompus)</th>
    <th>Montant non souscrit (rompus)</th>
    <th>Prime d'émission (€)</th>
    <th>Total valeur nominale par action (€)</th>
    <th>Montant total souscrit (€)</th>
    <th>Nombre d'actions post-AK</th>
    <th>% capital social post-AK</th>
  </tr>
   <% @firm.shareholders.order("created_at asc").each do |shareholder| %>
      <tr>
        <td><%= shareholder.first_name %> <%= shareholder.last_name %></td>
        <% if shareholder.initial_investor %>
          <td><%= number_with_delimiter(shareholder.investments.where(firm_id: @firm.id).first.amount.round(2), delimiter: " ", separator: ",", locale: :fr)%></td>
          <td><%= number_with_delimiter(shareholder.shares.to_f.round(2), delimiter: " ", separator: ",", locale: :fr) %></td>
          <td><%=((shareholder.shares.to_f/@firm.shareholders.where(initial_investor: true).sum('shares').to_f)*100).round(2)%> %</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
        <% else %>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td><%=number_with_delimiter(shareholder.investments.where(firm_id: @firm.id).first.amount.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
          <td><%=number_with_delimiter(shareholder.shares.round(2), delimiter: " ", separator: ",", locale: :fr)%></td>
          <td><%=shareholder.corrected_shares%></td>
          <td><%=number_with_delimiter(shareholder.non_subscribed_amount.round(2), delimiter: " ", separator: ",", locale: :fr)%></td>
          <td><%=number_with_delimiter((shareholder.corrected_shares * @firm.premium).round(2), delimiter: " ", separator: ",", locale: :fr)%></td>
          <td><%=number_with_delimiter((shareholder.corrected_shares * @firm.nominal_value).round(2), delimiter: " ", separator: ",", locale: :fr) %></td>
          <td><%=number_with_delimiter((shareholder.corrected_shares * @firm.real_value).round(2), delimiter: " ", separator: ",", locale: :fr) %></td>
        <% end %>
        <td><%=shareholder.corrected_shares %></td>
        <td><%=((shareholder.corrected_shares.to_f/@firm.shares.to_f)*100).round(2)%> %</td>
      </tr>
    <% end %>
    <tr class="active">
      <td><strong>Total</strong></td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: true).map(&:investments).sum{|investment| investment[0].amount}.round(2), delimiter: " ", separator: ",", locale: :fr)%> €</td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: true).sum('shares'), delimiter: " ", separator: ",", locale: :fr)%></td>
      <td>100.0 %</td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: false).map(&:investments).sum{|investment| investment[0].amount}, delimiter: " ", separator: ",", locale: :fr)%> €</td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: false).sum('shares').round(2), delimiter: " ", separator: ",", locale: :fr) %></td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: false).sum('corrected_shares'), delimiter: " ", separator: ",", locale: :fr) %></td>
      <td><%= number_with_delimiter(@firm.shareholders.where(initial_investor: false).sum('non_subscribed_amount').round(2), delimiter: " ", separator: ",", locale: :fr)%> €</td>
      <td><%= number_with_delimiter((@firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.premium).round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
      <td><%= number_with_delimiter((@firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.nominal_value).round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
      <td><%= number_with_delimiter((@firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.real_value).round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
      <td><%= number_with_delimiter(@firm.shareholders.sum('corrected_shares'), delimiter: " ", separator: ",", locale: :fr) %></td>
      <td><%=((@firm.shareholders.sum('corrected_shares').to_f/@firm.shares.to_f)*100).round(2)%> %</td>
    </tr>
</table>

<div class="row" id="line_items">
   <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Informations sur l'opération</h3>
        </div>
        <div class="panel-body">
          <p>Montant levé : <%= number_with_delimiter(@firm.rounds.last.amount_raised, delimiter: " ", separator: ",", locale: :fr) %> € (<%= @firm.rounds.last.ownership_offered%>% du capital ouvert)</p>
          <p>Valeur nominale de l'action : <%= @firm.nominal_value.round(2) %> €</p>
          <p>Prime d'émission <%= @firm.premium.round(2) %> €</p>
          <p>Nouveau prix de l'action : <%= number_with_delimiter(@firm.real_value.round(2), locale: :fr) %> €</p>
          <p>Valorisation pre-money : <%= number_with_delimiter(@firm.pre_valuation.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</p>
          <p>Valorisation post-money : <%= number_with_delimiter(@firm.post_valuation.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</p>
          <p>Part réelle du capital social ouvert aux nouveaux actionnaires : <%=((@firm.shareholders.where(initial_investor: false).sum('corrected_shares').to_f/@firm.shares.to_f)*100).round(2)%> %</p>
          <p>Date de la décision des associés : <%= @firm.rounds.last.date.strftime("%d %B %Y") %></p>
        </div>
      </div>
    </div>
</div>

</div>

app/views/firms/create_shareholder.js.erb
$('#shareholders').html("<%= j render 'showshareholders' %>")

app/views/firms/destroy_shareholder.js.erb
$('#shareholders').html("<%= j render 'showshareholders' %>")

app/views/firms/edit.html.erb
<h1>Editer les détails d'une société</h1>

<%= render 'form' %>

app/views/firms/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h2>Liste des sociétés ajoutées par <%= current_user.email %></h2>
  </div>
  <div class="col-sm-6">
    <%= button_to "Ajouter une nouvelle société", new_firm_path, method: 'get', class: "btn btn-lg btn-success pull-right"%>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    Une fois une société ajoutée, vous pouvez démarrer une augmentation de capital et générer les documents nécessaires.
  </div>
</div>

<table class="table table-hover firms-index-table">
  <th>Société</th>
  <th>Dernière édition</th>
  <th class="text-center">Tableau de capitalisation</th>
  <th class="text-center">Bulletins de souscription</th>
  <th></th>
  <% @firms.order("updated_at desc").each do |firm| %>
    <% if firm.user_id == current_user.id %>
      <tr>
        <td><h4><%=link_to firm.name, firm_path(firm)%></h4></td>
        <td><%=firm.updated_at.strftime("%d %B %Y à %H:%M")  %></td>
        <% if firm.rounds.count > 1 %>
          <td>
            <%= button_to "Voir le tableau", cap_table_path(firm), method: 'get', class: "btn btn-sm btn-primary center-block"%>
          </td>
          <td>
            <%= button_to "Voir les bulletins", subscription_forms_path(firm, Round.where(firm_id: firm.id).last), method: 'get', class: "btn btn-sm btn-primary center-block" %>
          </td>
          <td></td>
        <% else %>
          <td colspan="2"><%= button_to "Démarrer une augmentation de capital", new_round_path(firm), method: 'get', class: "btn btn-sm btn-success center-block"%>
          <td></td>

        <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/firms/show.html.erb
<div class="row">
  <div class="col-sm-5">
    <div class="row">
      <h1>Société '<%= @firm.name %>'</h1>
    </div>
    <div class="row">
      <p><%=link_to "Editer les détails de la société", edit_firm_path(@firm), method: 'get' %></p>
    </div>
  </div>

  <div class="col-sm-4 pull-right">
    <% if @firm.rounds.count > 1 %>
      <%= button_to "Voir l'opération en cours", show_round_path(@firm, Round.where(firm_id: @firm.id).last), method: 'get', class: "btn btn-lg btn-success center-block"%>
    <% else %>
      <%= button_to "Démarrer une augmentation de capital", new_round_path(@firm), method: 'get', class: "btn btn-success center-block"%>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Informations sur la société</h3>
      </div>
      <div class="panel-body">
        <div class="col-sm-6">
          <p>Adresse : <%=@firm.official_address%></p>
          <p>Numéro RCS : <%=@firm.rcs%> (greffe de <%=@firm.court_service%>)</p>
          <p>Banque : <%=@firm.bank_name%> (agence <%=@firm.bank_agency%>)</p>
          <p>Adresse de la banque : <%=@firm.bank_agency_address%></p>
          <p>Numéro de compte : <%=@bank_account%></p>
        </div>
        <div class="col-sm-6">
          <p>Capital social pré-augmentation de capital: <strong><%= number_with_delimiter(@firm.initial_capital.to_s, delimiter: " ", separator: ",", locale: :fr) %></strong> €</p>
          <p><strong><%=@firm.shares%></strong> actions en circulation</p>
          <p>Valeur nominale de <strong><%=@firm.nominal_value.round(2)%> €</strong></p>
        </div>
      </div>
    </div>
  </div>
  <% if @firm.rounds.count > 1 %>
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Infos sur la levée</h3>
        </div>
        <div class="panel-body">
          <p>
          Voir le tableau de capitalisation : <%= link_to "Format Web", cap_table_path(format: "html") %></p>
          <p>Télécharger le tableau de capitalisation : <%= link_to "Format Excel", cap_table_path(format: "xls") %></p>
          <p>Montant levé : <%= number_with_delimiter(@firm.rounds.last.amount_raised, delimiter: " ", separator: ",", locale: :fr) %> € (<%= @firm.rounds.last.ownership_offered%>% du capital ouvert)</p>
          <p>Nouveau prix de l'action : <%= number_with_delimiter(@firm.real_value.round(2), locale: :fr) %> €</p>
          <p>Prime d'émission <%= @firm.premium.round(2) %> €</p>
          <p>Valorisation pre-money : <%= number_with_delimiter(@firm.pre_valuation.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</p>
          <p>Valorisation post-money : <%= number_with_delimiter(@firm.post_valuation.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h3>Liste des actionnaires</h3>
<table class="table table-hover table-bordered table-condensed">
  <tr class="info">
    <th>Prénom</th>
    <th>Nom</th>
    <th>Nb d'actions détenues</th>
    <% if @firm.rounds.count > 1 %>
      <th>Nb d'actions détenues (rompus)</th>
      <th>Montant souscrit (rompus)</th>
      <th>Montant non-souscrit (rompus)</th>
      <th>Prime d'émission</th>
    <% end %>
    <% if @firm.rounds.count > 1 %>
      <th>Capital détenu (post-AK)</th>
    <% else %>
      <th>Capital détenu (pré-AK)</th>
    <% end %>
  </tr>
  <% @shareholders.order("created_at asc").each do |shareholder| %>
    <tr>
      <td><%= shareholder.first_name %></td>
      <td><%= shareholder.last_name %></td>
      <td><%= number_with_delimiter(shareholder.shares.round(2), delimiter: " ", separator: ",", locale: :fr) %> actions</td>

      <% if @firm.rounds.count > 1 && !shareholder.initial_investor %>
        <td><%= number_with_delimiter(shareholder.corrected_shares, delimiter: " ", separator: ",", locale: :fr) %> actions</td>
        <td><%= number_with_delimiter((shareholder.corrected_shares * @firm.real_value).round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
        <td><%= number_with_delimiter(shareholder.non_subscribed_amount.round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
        <td><%= number_with_delimiter((shareholder.corrected_shares * @firm.premium).round(2), delimiter: " ", separator: ",", locale: :fr) %> €</td>
      <% elsif @firm.rounds.count == 1 %>

      <% else %>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
      <% end %>
      <td><%= ((shareholder.shares.to_f/@firm.shares.to_f)*100).round(2)%>% </td>

    </tr>
  <% end %>
  <tr class="active">
    <td><strong>Total</strong></td>
    <td></td>
    <td><%=number_with_delimiter(@firm.shareholders.sum('shares').round(2), delimiter: " ", separator: ",", locale: :fr)%> actions</td>
    <% if @firm.rounds.count > 1 %>
      <td><%=number_with_delimiter(@firm.shareholders.sum('corrected_shares'), delimiter: " ", separator: ",", locale: :fr)%> actions</td>
      <td><%=number_with_delimiter((@firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.real_value).round(2), delimiter: " ", separator: ",", locale: :fr)%> €</td>
      <td><%=number_with_delimiter(@firm.shareholders.sum('non_subscribed_amount').round(2), delimiter: " ", separator: ",", locale: :fr)%> €</td>
      <td><%=number_with_delimiter((@firm.shareholders.where(initial_investor: false).sum('corrected_shares') * @firm.premium).round(2), delimiter: " ", separator: ",", locale: :fr)%> €</td>
    <% else %>

    <% end %>
    <td><%=((@firm.shareholders.sum('corrected_shares').to_f/@firm.shares.to_f)*100).round(2)%> %</td>
  </tr>
</table>
<div class="row">
  <div class="pull-right">
    <p><%= link_to "Supprimer la société", firm_path(@firm), method: 'delete'%></p>
  </div>
</div>