config/routes.rb
Rails.application.routes.draw do

  get 'presentation/show'

  root 'home#index', as: :home
  get 'presentation' => 'presentation#show', as: :presentation

  devise_for :users
  ActiveAdmin.routes(self)

  resources :firms
  get 'firms/:id/round/:round_id/ownership' => "firms#ownership", as: :ownership
  post 'firms/:id/round/:round_id/ownership' => "firms#update_ownership", as: :update_ownership
  get 'firms/:id/cap_table' => "firms#cap_table", as: :cap_table

  resources :shareholders, only: [:show, :edit, :update]
  get 'firms/:id/round/:round_id/shareholders' => 'shareholders#new', as: :new_shareholder
  post 'firms/:id/round/:round_id/shareholders/' => 'shareholders#create', as: :create_shareholder
  delete 'firms/:id/round/:round_id/shareholders/:shareholder_id' => 'shareholders#destroy', as: :delete_shareholder

  resources :rounds, only: [:edit, :update, :destroy]
  get 'firms/:id/rounds/new' => 'rounds#new', as: :new_round
  get 'firm/:id/round/:round_id' => 'rounds#show', as: :show_round
  post 'firm/:id/rounds' => 'rounds#create', as: :create_round
  get 'firms/:id/rounds' => 'rounds#index', as: :rounds

  get 'firms/:id/round/:round_id/subscription_forms' => 'subscription_forms#index', as: :subscription_forms
  get 'firms/:id/round/:round_id/subscription_form/:shareholder_id/:investment_id' => 'subscription_forms#show', as: :subscription_form
  get 'firms/:id/round/:round_id/subscription_form/zip' => 'subscription_forms#zip_form', as: :zip_form
end

app/models/shareholder.rb
class Shareholder < ActiveRecord::Base
  belongs_to :firm
  has_many :investments
  has_many :rounds, through: :investments
  has_many :subscription_forms
end

app/controllers/shareholders_controller.rb
class ShareholdersController < ApplicationController

  before_action :find_firm, only: [:new, :create, :destroy]
  before_action :find_round, only: [:new, :create, :destroy]
  respond_to :js, :html

  def new
    @shareholder = Shareholder.new
  end

  def show
  end

  def edit
  end

  def update
  end

  def create
    @shareholder = @firm.shareholders.create(shareholder_params)
    if @round.initial_round
      @shareholder.update_attribute(:initial_investor, true)
    else
      @shareholder.update_attribute(:initial_investor, false)
    end
    @round = Round.find(params[:round_id])
    respond_with do |format|
      format.js
    end
  end

  def destroy
    Shareholder.find(params[:shareholder_id]).destroy
    respond_with do |format|
      format.js
    end
  end

  private

    def find_firm
      @firm = Firm.find(params[:id])
    end

    def find_round
      @round = Round.find(params[:round_id])
    end

    def shareholder_params
      params.require(:shareholder).permit(:first_name, :last_name, :birth_date, :email, :address,
                    :nationality, :initial_investor, :city, :country, :postal_code)
    end


end

app/helpers/shareholders_helper.rb
module ShareholdersHelper
end

app/views/shareholders/_new_initial_shareholder.html.erb
<%= form_for Shareholder.new, url: create_shareholder_path, method: 'post', remote: true do |f| %>
  <%= f.label :first_name, "Prénom" %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name, "Nom" %>
  <%= f.text_field :last_name %>
  <%= f.label :birth_date, "Date de naissance" %>
  <%= f.date_select :birth_date, start_year: 1930 %>
  <%= f.label :address, "Adresse" %>
  <%= f.text_field :address %>
  <%= f.label :nationality, "Nationalité" %>
  <%= f.text_field :nationality %>
  <%= f.submit %>
<% end %>

app/views/shareholders/_new_shareholder.html.erb
<div class="form-group">
  <%= form_for Shareholder.new, url: create_shareholder_path, method: 'post', remote: true do |f| %>
    <% if @firm.rounds.count > 1 %>
      <legend class="text-center">Ajouter un nouvel actionnaire</legend>
    <% else %>
      <legend class="text-center">Ajouter un actionnaire initial</legend>
    <% end %>
    <div class="row">
      <div class="col-sm-6">
      <%= f.label :first_name, "Prénom" %>
      <%= f.text_field :first_name, class: "form-control", placeholder: 'Prénom' %>
      </div>
      <div class="col-sm-6">
      <%= f.label :last_name, "Nom" %>
      <%= f.text_field :last_name, class: "form-control", placeholder: 'Nom' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <%= f.label :nationality, "Nationalité" %>
        <%= f.text_field :nationality, class: "form-control", placeholder: 'Nationalité' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        <%= f.label :birth_date, "Date de naissance" %><br>
        <%= f.date_select :birth_date, start_year: 1930, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <%= f.label :address, "Adresse" %>
        <%= f.text_area :address, class: "form-control", rows: "3", placeholder: 'Adresse postale' %>
        <%= f.label :postal_code, "Code postal" %>
        <%= f.text_field :postal_code, class: "form-control", placeholder: 'Code postal' %>
      </div>
      <div class="col-sm-5">
        <div class="col-sm-12">
          <%= f.label :city, "Ville" %><br>
          <%= f.text_field :city, class: "form-control" %>
        </div>
        <div class="col-sm-12">
          <%= f.label :country, "Pays" %><br>
          <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="row last-row">
      <div class="col-sm-6 col-sm-offset-3">
          <% if @firm.rounds.count > 1 %>
            <%= f.submit "Ajouter un nouvel actionnaire", class: "btn btn-primary submit-button"%>
          <% else %>
            <%= f.submit "Ajouter un actionnaire initial", class: "btn btn-primary submit-button"%>
          <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/shareholders/_show_shareholders.html.erb
<% if @firm.shareholders.any? %>
    <% if @firm.rounds.count > 1 %>
      <legend>Liste des nouveaux actionnaires</legend>
    <% else %>
      <legend>Liste des actionnaires initiaux</legend>
    <% end %>
  <table class="table table-hover">
    <th>Prénom</th>
    <th>Nom</th>
    <th></th>
  <% @firm.shareholders.each do |shareholder| %>
    <% if (@round.initial_round && shareholder.initial_investor) || (!@round.initial_round && !shareholder.initial_investor) %>
        <tr>
          <td><%=shareholder.first_name%></td>
          <td><%=shareholder.last_name%></td>
          <td><%= link_to 'Supprimer', delete_shareholder_path(@firm, @round.id, shareholder), method: 'delete', remote: true %></td>
        </tr>
    <% end %>
  <%end%>
  </table>
  <hr>
  <% if @firm.rounds.count > 1 %>
      <div class="col-sm-8 col-sm-offset-2">
        <p class="text-center"><small>Tous les nouveaux actionnaires ont été ajoutés ?</small></p>
      </div>
      <%= button_to 'Définir les montants investis par les actionnaires', ownership_path(@firm, @round.id), method: 'get', class: "btn btn-success add-ownership-button center-block" %>
  <% else %>
      <div class="col-sm-8 col-sm-offset-2">
        <p class="text-center"><small>Tous les actionnaires initiaux ont été ajoutés ?</small></p>
      </div>
      <%= button_to 'Définir la répartition du capital (pré-levée)', ownership_path(@firm, @round.id), method: 'get', class: "btn btn-success add-ownership-button center-block" %>
  <% end %>
<% end %>

app/views/shareholders/create.js.erb
$('#shareholders').html("<%= j render 'show_shareholders' %>")
$('#new_shareholder').html("<%= j render 'new_shareholder' %>")

app/views/shareholders/create_round_shareholder.js.erb
$('#new_shareholders').html("<%= j render 'show_round_shareholders' %>")
$('#new_shareholder_form').html("<%= j render 'new_initial_shareholder' %>")

app/views/shareholders/destroy.js.erb
$('#shareholders').html("<%= j render 'show_shareholders' %>")

app/views/shareholders/new.html.erb
<% if @round.initial_round %>
  <h1>Ajouter les actionnaires initiaux de la société <%=@firm.name%></h1>


    <div class="row bs-wizard" style="border-bottom:0;">

      <div class="col-xs-2 col-xs-offset-1 bs-wizard-step complete">
        <div class="text-center bs-wizard-stepnum">Etape 1</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter une nouvelle société</div>
      </div>

      <div class="col-xs-2 bs-wizard-step active"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 2</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center"><strong>Ajouter les actionnaires initiaux</strong></div>
      </div>

      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 3</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir la répartition du capital pré-levée</div>
      </div>

      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 4</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter les nouveaux actionnaires</div>
      </div>

      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 5</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir les montants investis par les nouveaux actionnaires</div>
      </div>

    </div>


<% else %>
  <h1>Ajouter un nouvel actionnaire</h1>

    <div class="row bs-wizard" style="border-bottom:0;">

      <div class="col-xs-2 col-xs-offset-1 bs-wizard-step complete">
        <div class="text-center bs-wizard-stepnum">Etape 1</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter une nouvelle société</div>
      </div>

      <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 2</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter les actionnaires initiaux</div>
      </div>

      <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 3</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir la répartition du capital pré-levée</div>
      </div>

      <div class="col-xs-2 bs-wizard-step active"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 4</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center"><strong>Ajouter les nouveaux actionnaires</strong></div>
      </div>

      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 5</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir les montants investis par les nouveaux actionnaires</div>
      </div>

    </div>

<% end %>
  <hr>

<div class="row">
  <div class="col-sm-6 col-sm-offset-1">
    <div id="new-shareholder">
        <%= render 'new_shareholder' %>
    </div>
  </div>
  <div class="col-sm-4 ">
    <div id="shareholders">
      <%= render 'show_shareholders' %>
    </div>
  </div>
</div>