config/routes.rb
Rails.application.routes.draw do

  get 'presentation/show'

  root 'home#index', as: :home
  get 'presentation' => 'presentation#show', as: :presentation

  devise_for :users
  ActiveAdmin.routes(self)

  resources :firms
  get 'firms/:id/round/:round_id/ownership' => "firms#ownership", as: :ownership
  post 'firms/:id/round/:round_id/ownership' => "firms#update_ownership", as: :update_ownership
  get 'firms/:id/cap_table' => "firms#cap_table", as: :cap_table

  resources :shareholders, only: [:show, :edit, :update]
  get 'firms/:id/round/:round_id/shareholders' => 'shareholders#new', as: :new_shareholder
  post 'firms/:id/round/:round_id/shareholders/' => 'shareholders#create', as: :create_shareholder
  delete 'firms/:id/round/:round_id/shareholders/:shareholder_id' => 'shareholders#destroy', as: :delete_shareholder

  resources :rounds, only: [:edit, :update, :destroy]
  get 'firms/:id/rounds/new' => 'rounds#new', as: :new_round
  get 'firm/:id/round/:round_id' => 'rounds#show', as: :show_round
  post 'firm/:id/rounds' => 'rounds#create', as: :create_round
  get 'firms/:id/rounds' => 'rounds#index', as: :rounds

  get 'firms/:id/round/:round_id/subscription_forms' => 'subscription_forms#index', as: :subscription_forms
  get 'firms/:id/round/:round_id/subscription_form/:shareholder_id/:investment_id' => 'subscription_forms#show', as: :subscription_form
  get 'firms/:id/round/:round_id/subscription_form/zip' => 'subscription_forms#zip_form', as: :zip_form
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :firm
  has_many :investments
  has_many :shareholders, through: :investments
  has_many :subscription_forms
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  before_action :find_firm, only: [:new, :create, :show, :index]
  before_action :authenticate_user!

  def new
    @round = Round.new
  end

  def create
    @round = Round.create(round_params)
    @round.update_attribute(:initial_round, false)
    redirect_to new_shareholder_path(@firm.id, @round.id)
  end

  def show
    @round = Round.find(params[:round_id])
  end

  def index
    @rounds = @firm.rounds
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def find_firm
      @firm = Firm.find(params[:id])
    end

    def round_params
      params.require(:round).permit(:name, :ownership_offered, :firm_id, :date)
    end

    def set_amount(id)
      params.require(:investment).fetch(id).permit(:amount, :round_id)
    end

end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/destroy.html.erb
<h1>Rounds#destroy</h1>
<p>Find me in app/views/rounds/destroy.html.erb</p>

app/views/rounds/edit.html.erb
<h1>Rounds#edit</h1>
<p>Find me in app/views/rounds/edit.html.erb</p>

app/views/rounds/index.html.erb
<h1>Liste des opérations pour <%=@firm.name%></h1>

<table class="table table-hover">
  <th>Nom</th>
  <th>Date de création</th>
  <th>Dernière miseà jour</th>
  <% @rounds.each do |round| %>
    <tr>
      <% if !round.initial_round %>
        <td><%= link_to round.name, show_round_path(@firm.id, round.id) %>       <span class="label label-primary">AK</span>
        </td>
      <% else %>
        <td><%= link_to round.name, show_round_path(@firm.id, round.id) %></span>
      <% end %>
      <td><%=round.created_at.strftime("%d %B %Y à %H:%M")  %></td>
      <td><%=round.updated_at.strftime("%d %B %Y à %H:%M")  %></td>
    </tr>
  <% end %>
</table>

app/views/rounds/new.html.erb
<h2>Créer une opération d'augmentation de capital pour <%= @firm.name %></h2>
<hr>

      <div class="row bs-wizard" style="border-bottom:0;">

      <div class="col-xs-2 col-xs-offset-1 bs-wizard-step complete">
        <div class="text-center bs-wizard-stepnum">Etape 1</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter une nouvelle société</div>
      </div>

      <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 2</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter les actionnaires initiaux</div>
      </div>

      <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 3</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir la répartition du capital pré-levée</div>
      </div>

      <div class="col-xs-2 bs-wizard-step active"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 4</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center"><strong>Ajouter les nouveaux actionnaires</strong></div>
      </div>

      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 5</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Définir les montants investis par les nouveaux actionnaires</div>
      </div>
    </div>

  <hr>
  <div class="row">
<div class="col-sm-8 col-sm-offset-2">

<%= form_for @round, url: create_round_path, method: 'post' do |f| %>
  <div class="col-sm-8 col-sm-offset-1">
    <div class="row">
      <div class="form-group">
        <%= f.label :name, "Nom donné à l'opération", class: "control-label col-sm-4 text-right" %>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nom donné à l'opération" %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :name, "Date de la décision", class: "control-label col-sm-4 text-right" %>
        <div class="col-sm-8">
          <%= f.date_field :date, class: "form-control", placeholder: "Date de la décision"%>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="form-group">
        <%= f.label :ownership_offered, "Part du capital ouverte", class: "control-label col-sm-4 text-right" %>
        <div class="col-sm-6">
          <%= f.text_field :ownership_offered, class: "form-control", placeholder: "Part du capital ouverte (%)" %>
        </div>
      </div>
    </div>
    <br>
    <br>
  <%= f.hidden_field :firm_id, value: @firm.id %>
  <%= f.submit "Créer l'opération", class: 'btn btn-primary border-bottom center-block' %>
</div>
<% end %>
</div>
</div>

app/views/rounds/show.html.erb
<h1>Télécharger les documents de l'opération de <%= @firm.name %></h1>

  <div class="row bs-wizard" style="border-bottom:0;">
      <div class="col-xs-3 bs-wizard-step complete">
        <div class="text-center bs-wizard-stepnum">Etape 1</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Créer la société</div>
      </div>

      <div class="col-xs-3 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 2</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter les actionnaires initiaux</div>
      </div>

      <div class="col-xs-3 bs-wizard-step complete"><!-- complete -->
        <div class="text-center bs-wizard-stepnum">Etape 3</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <a href="#" class="bs-wizard-dot"></a>
        <div class="bs-wizard-info text-center">Ajouter les nouveaux actionnaires</div>
      </div>

        <div class="col-xs-3 bs-wizard-step active"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">Etape 4</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Télécharger les documents</div>
        </div>
    </div>
    <hr>


<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
  <%= button_to "Voir le tableau de capitalisation", cap_table_path(@firm.id), method: 'get', class: 'btn btn-success' %>
  </div>
  <div class="col-sm-4">
  <%= button_to "Voir les bulletins de souscription", subscription_forms_path(@firm.id, @round.id), method: 'get', class: 'btn btn-success' %>
  </div>
</div>
<br>
<br>
<br>
<% unless @round.initial_round %>
  <p class="lead"><%= @round.ownership_offered %>% ouvert pour un montant levé de <%=@round.amount_raised%> €</p>
<% end%>

app/views/rounds/update.html.erb
<h1>Rounds#update</h1>
<p>Find me in app/views/rounds/update.html.erb</p>